sudo: required
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t orachide/heketi-ui:latest -t orachide/heketi-ui:1.0.1 .
  - docker push orachide/heketi-ui:latest
  - docker push orachide/heketi-ui:1.0.1
